<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Version>0.4.2</Version>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\LazyForza.RaceServer.Protocol\LazyForza.RaceServer.Protocol.csproj" />
    <ProjectReference Include="..\LazyForza.RaceServer.Core\LazyForza.RaceServer.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Remove="data\**\*" />
    <None Remove="data\**\*" />
  </ItemGroup>
</Project>
